"""Tests for a13: Kannisto old-age closure.

THEORY under test: above roughly age 94 the Lee-Carter extrapolation inherits a
CONAPO extreme-age denominator artifact and produces a mortality curve that
*falls* with age. The closure must remove that without disturbing the ages
below it.
"""

from itertools import pairwise
from pathlib import Path

import numpy as np
import pytest

from backend.engine.a13_old_age_closure import (
    close_qx,
    fit_kannisto,
    kannisto_mx,
)
from backend.engine.exceptions import ActuarialValidationError

_DATA_DIR = Path(__file__).parent.parent / "data"
REAL_DEATHS = _DATA_DIR / "inegi" / "inegi_deaths.csv"
REAL_POP = _DATA_DIR / "conapo" / "conapo_population.csv"

# Same convention as test_open_interval_aggregate.py: anything asserting a
# property of the real Mexican fit has to stand down when only the synthetic
# fixtures are on disk, which is all CI ever has.
real_data = pytest.mark.skipif(
    not (REAL_DEATHS.exists() and REAL_POP.exists()),
    reason="real INEGI/CONAPO files not present (they are gitignored; see DATA.md)",
)


def _gompertz_mx(ages, a=2.5e-5, b=0.095):
    """A clean, strictly increasing hazard to use as a control."""
    return a * np.exp(b * np.asarray(ages, dtype=float))


class TestKannistoFit:
    def test_recovers_its_own_parameters(self):
        """THEORY: fitting data generated by Kannisto returns the generating a, b."""
        ages = np.arange(0, 101)
        a_true, b_true = 3.1e-5, 0.101
        mx = kannisto_mx(a_true, b_true, ages)

        a_hat, b_hat = fit_kannisto(ages, mx, fit_ages=(80, 93))

        assert a_hat == pytest.approx(a_true, rel=1e-6)
        assert b_hat == pytest.approx(b_true, rel=1e-6)

    def test_slope_is_positive_on_real_shaped_data(self):
        ages = np.arange(0, 101)
        _, b = fit_kannisto(ages, _gompertz_mx(ages), fit_ages=(80, 93))
        assert b > 0

    def test_rejects_a_window_too_small_to_fit(self):
        ages = np.arange(0, 101)
        with pytest.raises(ActuarialValidationError, match="at least 3"):
            fit_kannisto(ages, _gompertz_mx(ages), fit_ages=(90, 91))

    def test_rejects_rates_outside_the_logit_domain(self):
        ages = np.arange(0, 101)
        mx = _gompertz_mx(ages)
        mx[85] = 1.4  # more than one expected death per person-year
        with pytest.raises(ActuarialValidationError, match="0 < m_x < 1"):
            fit_kannisto(ages, mx, fit_ages=(80, 93))

    def test_rejects_a_decreasing_hazard(self):
        """THEORY: a closure with b <= 0 would reproduce the defect it exists to fix."""
        ages = np.arange(0, 101)
        mx = _gompertz_mx(ages)[::-1].copy()  # falling with age
        with pytest.raises(ActuarialValidationError, match="not positive"):
            fit_kannisto(ages, mx, fit_ages=(80, 93))


class TestKannistoHazard:
    def test_is_monotone_increasing(self):
        ages = np.arange(60, 111)
        mu = kannisto_mx(3e-5, 0.10, ages)
        assert np.all(np.diff(mu) > 0)

    def test_decelerates_unlike_gompertz(self):
        """THEORY: the logistic form flattens at the top; Gompertz does not.

        This is the long-tail behaviour the closure exists to reproduce.
        """
        ages = np.arange(80, 121)
        mu = kannisto_mx(3e-5, 0.10, ages)
        log_growth = np.diff(np.log(mu))
        # The proportional growth rate must itself be shrinking.
        assert np.all(np.diff(log_growth) < 0)
        assert np.all(mu < 1.0)  # a force of mortality that never explodes


class TestCloseQx:
    def test_leaves_ages_below_the_threshold_untouched(self):
        ages = np.arange(0, 101)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))
        closed = close_qx(ages, qx, closure_age=94)

        np.testing.assert_allclose(closed[:94], qx[:94], rtol=0, atol=0)

    def test_repairs_a_falling_tail(self):
        """THEORY: the exact defect found in the 2049 projection.

        q_x rose to age 94 and then fell away to age 99. After closure the
        whole tail must increase with age.
        """
        ages = np.arange(0, 101)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))
        # Reproduce the artifact: mortality declining above 94.
        for i, x in enumerate(ages):
            if x >= 94:
                qx[i] = qx[list(ages).index(94)] * (1.0 - 0.06 * (x - 94))
        assert qx[list(ages).index(98)] < qx[list(ages).index(94)]  # defect present

        closed = close_qx(ages, qx, closure_age=94)

        tail = closed[(ages >= 90) & (ages < 100)]
        assert np.all(np.diff(tail) > 0), "closed tail must increase with age"

    def test_forces_a_terminal_qx_of_one(self):
        ages = np.arange(0, 101)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))
        closed = close_qx(ages, qx, closure_age=94)
        assert closed[-1] == 1.0

    def test_stays_within_zero_and_one(self):
        ages = np.arange(0, 101)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))
        closed = close_qx(ages, qx, closure_age=94)
        assert np.all(closed >= 0.0) and np.all(closed <= 1.0)

    def test_is_a_no_op_when_the_table_ends_below_the_threshold(self):
        ages = np.arange(0, 91)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))
        closed = close_qx(ages, qx, closure_age=94)
        np.testing.assert_allclose(closed, qx)

    def test_is_idempotent(self):
        """THEORY: closing an already-closed table changes nothing.

        The fit window (80-93) lies entirely below the closure age (94), so a
        second pass refits on identical data and must reproduce the identical
        tail. If a re-run drifted the table, every pipeline that closes
        defensively at more than one layer would slowly corrupt the tail.
        """
        ages = np.arange(0, 101)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))

        once = close_qx(ages, qx, closure_age=94)
        twice = close_qx(ages, once, closure_age=94)

        np.testing.assert_allclose(twice, once, rtol=1e-12, atol=0)

    def test_fit_window_overlapping_the_closure_age_still_closes_soundly(self):
        """THEORY: nothing forbids fit_ages reaching past closure_age, and the
        fit then uses raw pre-closure rates for those ages. Even so, the
        closure's contract must hold: ages below closure untouched, tail
        monotone increasing, all rates in [0, 1], terminal q = 1.
        """
        ages = np.arange(0, 101)
        qx = 1.0 - np.exp(-_gompertz_mx(ages))

        closed = close_qx(ages, qx, fit_ages=(88, 97), closure_age=94)

        np.testing.assert_allclose(closed[:94], qx[:94], rtol=0, atol=0)
        tail = closed[ages >= 90]
        assert np.all(np.diff(tail[:-1]) > 0)  # monotone up to the forced terminal
        assert closed[-1] == 1.0
        assert np.all(closed >= 0.0) and np.all(closed <= 1.0)

    def test_reproduces_the_fitting_window_closely(self):
        """THEORY: a closure that cannot reproduce the ages it was fitted on
        has no business extrapolating beyond them."""
        ages = np.arange(0, 101)
        mx = _gompertz_mx(ages)
        qx = 1.0 - np.exp(-mx)

        a, b = fit_kannisto(ages, mx, fit_ages=(80, 93))
        window = (ages >= 80) & (ages <= 93)
        predicted = 1.0 - np.exp(-kannisto_mx(a, b, ages[window]))

        assert np.max(np.abs(predicted - qx[window])) < 0.01


@real_data
class TestOnTheRealProjection:
    """The defect as it actually appeared, on the real Mexican fit.

    Every case here reads year 2049, which exists only because the real INEGI
    window (1990-2019) projects 30 years past its end. On the mock fixtures the
    projection stops at 2040 and each case died on a range error -- a false
    failure that says nothing about the closure.
    """

    @pytest.fixture(scope="class")
    def projection(self):
        from backend.api.services.precomputed import get_projection, load_all

        load_all()
        return get_projection("unisex")

    def test_raw_extrapolation_still_falls_with_age(self, projection):
        """THEORY: the artifact is real and the closure is not fixing a phantom.

        Guards against a future data refresh silently removing the problem and
        leaving the closure switched on for no reason -- if this test starts
        failing, re-examine whether the closure is still needed.
        """
        lt = projection.to_life_table(year=2049, close_old_age=False)
        q94 = lt.q_x[94]
        q98 = lt.q_x[98]
        assert q98 < q94, "expected the uncorrected extrapolation to decline"

    def test_closed_projection_increases_through_the_tail(self, projection):
        lt = projection.to_life_table(year=2049)
        tail = [lt.q_x[x] for x in range(90, 100)]
        assert all(b > a for a, b in pairwise(tail)), tail

    def test_closure_does_not_disturb_working_ages(self, projection):
        """THEORY: pricing at ordinary ages must be unaffected by the closure."""
        closed = projection.to_life_table(year=2049)
        raw = projection.to_life_table(year=2049, close_old_age=False)
        for x in range(0, 94):
            assert closed.q_x[x] == pytest.approx(raw.q_x[x], rel=1e-12)

    def test_closed_table_satisfies_life_table_invariants(self, projection):
        """THEORY: the closure must hand a01 a table that still honours its
        contract — sum(d_x) = l_0, terminal q = 1, every q_x in [0, 1] — and
        l_x must be non-increasing with d_x = l_x - l_{x+1} consistent.
        A closure that repaired the tail but broke conservation of lives
        would poison every commutation downstream.
        """
        lt = projection.to_life_table(year=2049)
        v = lt.validate()
        assert v["sum_deaths_equals_l0"]
        assert v["terminal_mortality_is_one"]
        assert v["all_rates_valid"]

        ages = sorted(lt.l_x)
        lx = [lt.l_x[a] for a in ages]
        assert all(b <= a for a, b in pairwise(lx)), "l_x must be non-increasing"
        for a, a_next in pairwise(ages):
            assert lt.d_x[a] == pytest.approx(lt.l_x[a] - lt.l_x[a_next], abs=1e-9)

    def test_close_old_age_false_is_the_untouched_extrapolation(self, projection):
        """THEORY: close_old_age=False must reproduce the pre-fix behaviour
        exactly — q_x = 1 - exp(-exp(a_x + b_x * k_t)) straight off the
        Lee-Carter parameters, with only the terminal q forced to 1. If the
        escape hatch quietly applied any correction, the before/after
        comparisons on this page (and the regression guard above) would be
        comparing the closure against itself.
        """
        year = 2049
        raw = projection.to_life_table(year=year, close_old_age=False)

        year_idx = list(projection.projected_years).index(year)
        kt = projection.kt_central[year_idx]
        lc = projection.lee_carter
        expected_qx = 1.0 - np.exp(-np.exp(lc.ax + lc.bx * kt))
        expected_qx[-1] = 1.0
        expected_qx = np.clip(expected_qx, 0.0, 1.0)

        for i, age in enumerate(np.asarray(lc.ages, dtype=int)):
            assert raw.q_x[int(age)] == pytest.approx(expected_qx[i], rel=1e-12)
